baseurl = "http://mgdelacroix.es/"
languageCode = "en-us"
title = "Core dump"
paginate = 5
copyright = ""
theme = "after-dark"

[params]
    powered_by = false

[[menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/"

[[menu.main]]
    name = "Blog"
    weight = 2
    identifier = "blog"
    url = "/post"