#!/usr/bin/env bash
set -e

PAGES_BRANCH=gh-pages
PAGES_DIR=pages
DATE=`date +%Y%m%d-%H%M`

rm -rf public
hugo
git worktree add $PAGES_DIR $PAGES_BRANCH
rsync -av --delete public $PAGES_DIR --exclude .gitignore
(cd $PAGES_DIR && \
     git commit -a -m "$DATE" && \
     git push origin $PAGES_BRANCH)
rm -rf $PAGES_DIR
git worktree prune
