#!/usr/bin/env bash
set -e

PAGES_BRANCH=master
PAGES_DIR=pages
DATE=`date +%Y%m%d-%H%M`

git worktree add $PAGES_DIR $PAGES_BRANCH
hugo --destination $PAGES_DIR
(cd $PAGES_DIR && \
     git commit -a -m "$DATE" && \
     git push origin $PAGES_BRANCH)
rm -rf $PAGES_DIR
git worktree prune
